In [2]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [3]:
df=pd.read_csv("news.csv", index_col=None)

In [4]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [5]:
dataset=df.drop("Unnamed: 0", axis=1)

In [6]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [7]:
y=dataset["label"]

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(dataset['text'],y,test_size=0.33,random_state=53)

In [12]:
# here for hashingVectorizer we don't need to do the fit_transform, as it can map the text directly to vector using hashing function so transform can be used 
hash_vectorizer=HashingVectorizer(stop_words='english',alternate_sign=False)
hash_X_train=hash_vectorizer.transform(X_train)
hash_X_test=hash_vectorizer.transform(X_test)
print(hash_X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119222 stored elements and shape (4244, 1048576)>
  Coords	Values
  (1, 26381)	0.1336306209562122
  (1, 46353)	0.1336306209562122
  (1, 76282)	0.1336306209562122
  (1, 124604)	0.1336306209562122
  (1, 271872)	0.2672612419124244
  (1, 354766)	0.1336306209562122
  (1, 355578)	0.1336306209562122
  (1, 380136)	0.2672612419124244
  (1, 399927)	0.1336306209562122
  (1, 413315)	0.2672612419124244
  (1, 421751)	0.2672612419124244
  (1, 452780)	0.1336306209562122
  (1, 506429)	0.5345224838248488
  (1, 612563)	0.1336306209562122
  (1, 615897)	0.1336306209562122
  (1, 626851)	0.1336306209562122
  (1, 639862)	0.1336306209562122
  (1, 691517)	0.1336306209562122
  (1, 740856)	0.1336306209562122
  (1, 777362)	0.2672612419124244
  (1, 798576)	0.1336306209562122
  (1, 907820)	0.2672612419124244
  (1, 1039472)	0.1336306209562122
  (2, 14361)	0.3333333333333333
  (2, 81229)	0.3333333333333333
  :	:
  (4243, 924171)	0.08478501284163323
  (4243, 934801)	0.028261670947211076
  (4243, 935153)	0.028261670947211076
  (4243, 935275)	0.028261670947211076
  (4243, 939307)	0.1130466837888443
  (4243, 946139)	0.028261670947211076
  (4243, 949760)	0.028261670947211076
  (4243, 953107)	0.028261670947211076
  (4243, 958756)	0.028261670947211076
  (4243, 958992)	0.028261670947211076
  (4243, 963256)	0.028261670947211076
  (4243, 963865)	0.028261670947211076
  (4243, 975215)	0.028261670947211076
  (4243, 982957)	0.14130835473605538
  (4243, 993015)	0.028261670947211076
  (4243, 1004174)	0.028261670947211076
  (4243, 1004879)	0.028261670947211076
  (4243, 1009763)	0.05652334189442215
  (4243, 1010115)	0.028261670947211076
  (4243, 1017691)	0.028261670947211076
  (4243, 1026684)	0.028261670947211076
  (4243, 1027460)	0.028261670947211076
  (4243, 1038430)	0.028261670947211076
  (4243, 1039483)	0.028261670947211076
  (4243, 1044795)	0.05652334189442215

In [13]:
# model creation
clf=MultinomialNB()
clf.fit(hash_X_train,Y_train)
pred=clf.predict(hash_X_test)
score=metrics.accuracy_score(Y_test,pred)
print("accuracy:%0.3f"%score)
cm=metrics.confusion_matrix(Y_test,pred,labels=["FAKE","REAL"])

accuracy:0.853

In [16]:
print(cm)

[[ 733  275]
 [  33 1050]]

In [17]:
from sklearn.metrics import classification_report
report=classification_report(Y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.79      0.97      0.87      1083

    accuracy                           0.85      2091
   macro avg       0.87      0.85      0.85      2091
weighted avg       0.87      0.85      0.85      2091

In [18]:
# prediction process
dataset["text"][1]

'Google Pinterest Digg Linkedin Reddit Stumbleupon Print Delicious Pocket Tumblr \nThere are two fundamental truths in this world: Paul Ryan desperately wants to be president. And Paul Ryan will never be president. Today proved it. \nIn a particularly staggering example of political cowardice, Paul Ryan re-re-re-reversed course and announced that he was back on the Trump Train after all. This was an aboutface from where he was a few weeks ago. He had previously declared he would not be supporting or defending Trump after a tape was made public in which Trump bragged about assaulting women. Suddenly, Ryan was appearing at a pro-Trump rally and boldly declaring that he already sent in his vote to make him President of the United States. It was a surreal moment. The figurehead of the Republican Party dosed himself in gasoline, got up on a stage on a chilly afternoon in Wisconsin, and lit a match. . @SpeakerRyan says he voted for @realDonaldTrump : “Republicans, it is time to come home” https://t.co/VyTT49YvoE pic.twitter.com/wCvSCg4a5I \n— ABC News Politics (@ABCPolitics) November 5, 2016 \nThe Democratic Party couldn’t have asked for a better moment of film. Ryan’s chances of ever becoming president went down to zero in an instant. In the wreckage Trump is to leave behind in his wake, those who cravenly backed his campaign will not recover. If Ryan’s career manages to limp all the way to 2020, then the DNC will have this tape locked and loaded to be used in every ad until Election Day. \nThe ringing endorsement of the man he clearly hates on a personal level speaks volumes about his own spinelessness. Ryan has postured himself as a “principled” conservative, and one uncomfortable with Trump’s unapologetic bigotry and sexism. However, when push came to shove, Paul Ryan – like many of his colleagues – turned into a sniveling appeaser. After all his lofty tak about conviction, his principles were a house of cards and collapsed with the slightest breeze. \nWhat’s especially bizarre is how close Ryan came to making it through unscathed. For months the Speaker of the House refused to comment on Trump at all. His strategy seemed to be to keep his head down, pretend Trump didn’t exist, and hope that nobody remembered what happened in 2016. Now, just days away from the election, he screwed it all up. \nIf 2016’s very ugly election has done any good it’s by exposing the utter cowardice of the Republicans who once feigned moral courage. A reality television star spit on them, hijacked their party, insulted their wives, and got every last one of them to kneel before him. What a turn of events. \nFeatured image via Twitter'

In [19]:
# here for hashingVectorizer we don't need to do the fit_transform, as it can map the text directly to vector using hashing function so transform can be used 
hash_vectorizer=HashingVectorizer(stop_words='english',alternate_sign=False)
hash_X_train=hash_vectorizer.transform(X_train)
hash_X_test=hash_vectorizer.transform(X_test)

In [20]:
X_test[[6332]]

6332     Anti-Trump Protesters Are Tools of the Oligar...
Name: text, dtype: object

In [21]:
hash_X_test.shape

(2091, 1048576)

In [22]:
6332 in X_test.index

True

In [23]:
pos=X_test.index.get_loc(6332)
print(pos)

952

In [24]:
clf.predict(hash_X_test[952:953])

array(['FAKE'], dtype='<U4')