In [17]:
import pandas as pd
import numpy as np 
import itertools
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [18]:
df=pd.read_csv("news.csv", index_col=None)

In [19]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [20]:
dataset=df.drop("Unnamed: 0", axis=1)

In [21]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [22]:
y=dataset["label"]

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(dataset['text'],y,test_size=0.33,random_state=53)

In [24]:
tfidf=TfidfVectorizer(stop_words='english')
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)
print(X_train_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1119820 stored elements and shape (4244, 56922)>
  Coords	Values
  (1, 42470)	0.07711040274149526
  (1, 12105)	0.15008066461476866
  (1, 54177)	0.13782629144711137
  (1, 50628)	0.061296988343109586
  (1, 15924)	0.3479045460649079
  (1, 44520)	0.4973826512693341
  (1, 51896)	0.11596517664605868
  (1, 35783)	0.30902690818827977
  (1, 35256)	0.12628385718450857
  (1, 21881)	0.21271688045815978
  (1, 42534)	0.06081715886809217
  (1, 8399)	0.08729542880625335
  (1, 29531)	0.1454406205718245
  (1, 15927)	0.4973826512693341
  (1, 25686)	0.13550453594288983
  (1, 49203)	0.1672740861784377
  (1, 16814)	0.10404977746548139
  (1, 36087)	0.12648679854389897
  (1, 21568)	0.1007920919566398
  (1, 25684)	0.1030420922189754
  (1, 38823)	0.06048803110658644
  (1, 47506)	0.14539060877460044
  (1, 36831)	0.10772488937433067
  (2, 16972)	0.1606296088662543
  (2, 762)	0.48803966069171073
  :	:
  (4243, 41435)	0.02969665315895183
  (4243, 53607)	0.044665186536595916
  (4243, 659)	0.04293180970016178
  (4243, 38834)	0.037049324915825195
  (4243, 19003)	0.034437531050342904
  (4243, 11415)	0.04265300938931862
  (4243, 7545)	0.053202747014157864
  (4243, 22426)	0.04959478008035461
  (4243, 54007)	0.05100432396345157
  (4243, 7113)	0.055528486204784254
  (4243, 4932)	0.03711812880176506
  (4243, 39497)	0.04927770384099252
  (4243, 50053)	0.06673585515177109
  (4243, 38849)	0.048120818264389215
  (4243, 20702)	0.04867858477282518
  (4243, 42139)	0.04664685644842381
  (4243, 17247)	0.06113217067827768
  (4243, 50052)	0.05623192165966151
  (4243, 55228)	0.05623192165966151
  (4243, 29255)	0.05372450273788263
  (4243, 49435)	0.04265300938931862
  (4243, 11257)	0.06673585515177109
  (4243, 52945)	0.0644101159611447
  (4243, 20905)	0.05880643148765128
  (4243, 7962)	0.06673585515177109

In [25]:
len(tfidf.get_feature_names_out())

56922

In [26]:
print(X_train_tfidf.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [31]:
# model using multinomial
clf=MultinomialNB()
clf.fit(X_train_tfidf,Y_train)
pred=clf.predict(X_test_tfidf)
score=metrics.accuracy_score(Y_test,pred)
print("accuracy: %0.3f"%score)
cm=metrics.confusion_matrix(Y_test,pred,labels=["FAKE","REAL"])

accuracy: 0.857

In [32]:
cm

array([[ 739,  269],
       [  31, 1052]])

In [35]:
from sklearn.metrics import classification_report
report=classification_report(Y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.80      0.97      0.88      1083

    accuracy                           0.86      2091
   macro avg       0.88      0.85      0.85      2091
weighted avg       0.88      0.86      0.85      2091

In [36]:
# Prediction process 
dataset["text"][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entire left-wing establishment will form a lynch mob if they continue going after Hillary. And the FBI’s credibility is being attacked by the media and the Democrats to preemptively head off the results of the investigation of the Clinton Foundation and Hillary Clinton. \nThe covert struggle between FBI agents and Obama’s DOJ people has gone explosively public. \nThe New York Times has compared Comey to J. Edgar Hoover. Its bizarre headline, “James Comey Role Recalls Hoover’s FBI, Fairly or Not” practically admits up front that it’s spouting nonsense. The Boston Globe has published a column calling for Comey’s resignation. Not to be outdone, Time has an editorial claiming that the scandal is really an attack on all women. \nJames Carville appeared on MSNBC to remind everyone that he was still alive and insane. He accused Comey of coordinating with House Republicans and the KGB. And you thought the “vast right wing conspiracy” was a stretch. \nCountless media stories charge Comey with violating procedure. Do you know what’s a procedural violation? Emailing classified information stored on your bathroom server. \nSenator Harry Reid has sent Comey a letter accusing him of violating the Hatch Act. The Hatch Act is a nice idea that has as much relevance in the age of Obama as the Tenth Amendment. But the cable news spectrum quickly filled with media hacks glancing at the Wikipedia article on the Hatch Act under the table while accusing the FBI director of one of the most awkward conspiracies against Hillary ever. \nIf James Comey is really out to hurt Hillary, he picked one hell of a strange way to do it. \nNot too long ago Democrats were breathing a sigh of relief when he gave Hillary Clinton a pass in a prominent public statement. If he really were out to elect Trump by keeping the email scandal going, why did he trash the investigation? Was he on the payroll of House Republicans and the KGB back then and playing it coy or was it a sudden development where Vladimir Putin and Paul Ryan talked him into taking a look at Anthony Weiner’s computer? \nEither Comey is the most cunning FBI director that ever lived or he’s just awkwardly trying to navigate a political mess that has trapped him between a DOJ leadership whose political futures are tied to Hillary’s victory and his own bureau whose apolitical agents just want to be allowed to do their jobs. \nThe only truly mysterious thing is why Hillary and her associates decided to go to war with a respected Federal agency. Most Americans like the FBI while Hillary Clinton enjoys a 60% unfavorable rating. \nAnd it’s an interesting question. \nHillary’s old strategy was to lie and deny that the FBI even had a criminal investigation underway. Instead her associates insisted that it was a security review. The FBI corrected her and she shrugged it off. But the old breezy denial approach has given way to a savage assault on the FBI. \nPretending that nothing was wrong was a bad strategy, but it was a better one that picking a fight with the FBI while lunatic Clinton associates try to claim that the FBI is really the KGB. \nThere are two possible explanations. \nHillary Clinton might be arrogant enough to lash out at the FBI now that she believes that victory is near. The same kind of hubris that led her to plan her victory fireworks display could lead her to declare a war on the FBI for irritating her during the final miles of her campaign. \nBut the other explanation is that her people panicked. \nGoing to war with the FBI is not the behavior of a smart and focused presidential campaign. It’s an act of desperation. When a presidential candidate decides that her only option is to try and destroy the credibility of the FBI, that’s not hubris, it’s fear of what the FBI might be about to reveal about her. \nDuring the original FBI investigation, Hillary Clinton was confident that she could ride it out. And she had good reason for believing that. But that Hillary Clinton is gone. In her place is a paranoid wreck. Within a short space of time the “positive” Clinton campaign promising to unite the country has been replaced by a desperate and flailing operation that has focused all its energy on fighting the FBI. \nThere’s only one reason for such bizarre behavior. \nThe Clinton campaign has decided that an FBI investigation of the latest batch of emails poses a threat to its survival. And so it’s gone all in on fighting the FBI. It’s an unprecedented step born of fear. It’s hard to know whether that fear is justified. But the existence of that fear already tells us a whole lot. \nClinton loyalists rigged the old investigation. They knew the outcome ahead of time as well as they knew the debate questions. Now suddenly they are no longer in control. And they are afraid. \nYou can smell the fear. \nThe FBI has wiretaps from the investigation of the Clinton Foundation. It’s finding new emails all the time. And Clintonworld panicked. The spinmeisters of Clintonworld have claimed that the email scandal is just so much smoke without fire. All that’s here is the appearance of impropriety without any of the substance. But this isn’t how you react to smoke. It’s how you respond to a fire. \nThe misguided assault on the FBI tells us that Hillary Clinton and her allies are afraid of a revelation bigger than the fundamental illegality of her email setup. The email setup was a preemptive cover up. The Clinton campaign has panicked badly out of the belief, right or wrong, that whatever crime the illegal setup was meant to cover up is at risk of being exposed. \nThe Clintons have weathered countless scandals over the years. Whatever they are protecting this time around is bigger than the usual corruption, bribery, sexual assaults and abuses of power that have followed them around throughout the years. This is bigger and more damaging than any of the allegations that have already come out. And they don’t want FBI investigators anywhere near it. \nThe campaign against Comey is pure intimidation. It’s also a warning. Any senior FBI people who value their careers are being warned to stay away. The Democrats are closing ranks around their nominee against the FBI. It’s an ugly and unprecedented scene. It may also be their last stand. \nHillary Clinton has awkwardly wound her way through numerous scandals in just this election cycle. But she’s never shown fear or desperation before. Now that has changed. Whatever she is afraid of, it lies buried in her emails with Huma Abedin. And it can bring her down like nothing else has.  '

In [37]:
# text is converted to vector before the testing prediction
tfidf=TfidfVectorizer(stop_words="english")
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)

In [38]:
X_train_tfidf[[0]]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 56922)>

In [39]:
print(X_test_tfidf)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 533697 stored elements and shape (2091, 56922)>
  Coords	Values
  (0, 2385)	0.04673510209222487
  (0, 3184)	0.06954723147734826
  (0, 4067)	0.05666340098468139
  (0, 4919)	0.04824871588215696
  (0, 5460)	0.15762013389393498
  (0, 7383)	0.058563792627012654
  (0, 7422)	0.06994531311121911
  (0, 7464)	0.09887000461121552
  (0, 10525)	0.03238028580548933
  (0, 10673)	0.1000711492265641
  (0, 10984)	0.07780444275234664
  (0, 10985)	0.1612727978010528
  (0, 12457)	0.06547534804793215
  (0, 12601)	0.07881006694696749
  (0, 13343)	0.09568195059113496
  (0, 14163)	0.038181501713474654
  (0, 14446)	0.130821972163052
  (0, 14867)	0.034681321392149966
  (0, 15085)	0.0971987263420166
  (0, 15285)	0.09568195059113496
  (0, 15812)	0.04537185367441499
  (0, 15870)	0.036221638456254444
  (0, 15942)	0.25431588191329985
  (0, 16027)	0.5086317638265997
  (0, 16580)	0.04730867818016224
  :	:
  (2090, 52119)	0.0381402419774901
  (2090, 52134)	0.1579281887482439
  (2090, 52193)	0.08431789970864959
  (2090, 52290)	0.046040151863149324
  (2090, 52661)	0.044255374872908954
  (2090, 52926)	0.042928374280680325
  (2090, 52948)	0.05458150841413232
  (2090, 53308)	0.04765338611681571
  (2090, 53607)	0.05037501154084796
  (2090, 53792)	0.09080298635623373
  (2090, 54120)	0.07896409437412195
  (2090, 54171)	0.06189721311148678
  (2090, 54393)	0.046951871264186394
  (2090, 54647)	0.10349300134432479
  (2090, 54699)	0.05368394292621844
  (2090, 54746)	0.02982714578864243
  (2090, 54822)	0.05487684521949254
  (2090, 54850)	0.03996993475945496
  (2090, 54936)	0.07164009893565843
  (2090, 55614)	0.023760398860929715
  (2090, 55764)	0.0648726619727553
  (2090, 55773)	0.0518801900971171
  (2090, 55858)	0.030101865375028892
  (2090, 56196)	0.02405402346607664
  (2090, 56512)	0.04148160985129049

In [40]:
# wanted to test the output for X_test sample in index 6331
X_test[[6331]]

6331    The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
Name: text, dtype: object

In [42]:
X_test_tfidf.shape

(2091, 56922)

In [43]:
6331 in X_test.index

True

In [44]:
# finding the exact row position of X_test sample
pos=X_test.index.get_loc(6331)
print(pos)

737

In [45]:
clf.predict(X_test_tfidf[737:738])

array(['FAKE'], dtype='<U4')